### ISSUE TITLE
DOC: Better wording to describe "3DR Services" on http://android.dronekit.io/

### ISSUE THREAD

**Issue by hamishwillee** [DroidPlanner/DroneKit-Android#104]
http://android.dronekit.io/ or [index.rst](https://github.com/DroidPlanner/DroneKit-Android/blob/develop/doc/index.rst) 

The second paragraph should be swapped with the last paragraph (is "least important" information for developers)

The word "guide" in the second paragraph isn't quite right because it implies "instructions" rather than "listing"

    The guide to apps built with DroneKit can be found 
    on the Google Play Store under the name: 3DR Services.

Catalog (or even listing) would be better. So:

    The catalog of apps built with DroneKit can be found 
    on the Google Play Store under the name: 3DR Services.

or 

    A catalog of all DroneKit apps on the Google Play Store can be found in 3DR Services.

**Comment by hamishwillee** [comment]
Fixed #105

**Comment by ne0fhyk** [comment]
Fixed by #105
