### ISSUE TITLE
Doc: Delete the built HTML in the repo?

### ISSUE THREAD

**Issue by hamishwillee** [DroidPlanner/DroneKit-Android#107]
It is not normal to also upload the built HTML in the same tree - is this intentional?

Propose changes:

* Delete the build tree from the repo
* Add the build tree to .gitignore
* Add *~ to .gitignore so temporary files are not shown in git

**Comment by mrpollo** [comment]
Agreed, only that the current doc build process needs to be looked at again, @ne0fhyk can we talk offline before we decide on what to do on this ?

**Comment by ne0fhyk** [comment]
@hamishwillee the built html was needed before so that they could automatically be uploaded to the gihutb pages branch. Now that everything is on the DroneKit site, they can be removed.

@mrpollo correct me if i'm wrong, but your update script only needs access to the `rst` files, right?

**Comment by mrpollo** [comment]
yes, you can remove the _build folder

**Comment by hamishwillee** [comment]
Setting as closed - this is addressed by #108
