### ISSUE TITLE
Ignore component id other than the autopilot's

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/DroneKit-Android#124]
Autopilot component id is `1`. Any other component id should be ignored, or specifically white-listed.

**Comment by walmis** [comment]
This causes issues when a storm32 gimbal is connected over mavlink in APM 3.3.

Any updates on this?

https://github.com/DroidPlanner/Tower/issues/1523

**Comment by squilter** [comment]
Fixed with #205
