### ISSUE TITLE
【Compile Error】Can you tell me how to solve it?

### ISSUE THREAD

**Issue by Linjieqiang** [DroidPlanner/DroneKit-Android#153]
Hello,Thanks for your work.But I want to express,why I always failed when I try to compile this project.And the error information is that " Error:Execution failed for task ':ServiceApp:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_45\bin\java.exe'' finished with non-zero exit value 1"
Can you tell me how to solve it?I am looking forward to your answer.

**Comment by ne0fhyk** [comment]
Could you attempt to compile using java 7 instead.

--
Fredia Huya-Kouadio
Senior Android Engineer, 3D Robotics
fredia@3dr.com

**Comment by Linjieqiang** [comment]
But I compiled Tower is fine . Did you compile using  java 7 ?

**Comment by Linjieqiang** [comment]
OK ! I am excited to feedback that when I compile with java7 ,it's no error ! Thanks !
