### ISSUE TITLE
For Hello Drone app, getting Drone Disconnected/ Connection Failed: only on emulator 

### ISSUE THREAD

**Issue by csathe** [DroidPlanner/DroneKit-Android#163]
Hello, 

I am getting Drone Disconnected/ Connection Failed: only on emulator  for the Hello Drone app.  I confirmed details like correct ip while launching STIL simulation, STIL simulation correctly running (Ready to FLY, received 510 parameters) etc. The same setup works on real Android devices. 
For emulator I tried using both 127.0.0.1 and the ip listed in About Device on the Android emulator. (in below screenshot 10.0.2.15 is the ip listed in About Phone on the emulator)
Am I missing something ? Can someone please help with a potential solution ? 

![screen shot 2015-06-06 at 9 56 55 am](https://cloud.githubusercontent.com/assets/8527193/8020753/b79f48d4-0c39-11e5-840a-2cbaad0c5bf7.png)

![screen shot 2015-06-06 at 10 42 53 am](https://cloud.githubusercontent.com/assets/8527193/8020766/fd658f0e-0c39-11e5-9f5c-4bab84d04e89.png)

![screen shot 2015-06-06 at 9 49 09 am](https://cloud.githubusercontent.com/assets/8527193/8020768/01861284-0c3a-11e5-9469-fb4faaf41df7.png)

**Comment by ne0fhyk** [comment]
I have yet to successfully be able to get the default android emulator taking to sitl on the local network. 
Instead, I have used genymotion when testing via emulation.

**Comment by squilter** [comment]
I don't think this can be done through the emulator without any complicated port forwarding.  I just booted up the emulator, and it didn't have an external ip-address on the LAN.  It forwarded in some weird way through the computer, so I couldn't get packets there.

As @ne0fhyk said, genymotion does work.  It just opens op android in a virtualbox, which does give it a proper external ip-address.

**Comment by ne0fhyk** [comment]
Closing issue as alternative solution was suggested.
