### ISSUE TITLE
Setting Region of Interest while in guided flight mode.

### ISSUE THREAD

**Issue by Teemperor** [DroidPlanner/DroneKit-Android#166]
Is there a way to set the region of interest while the drone is in the guided flight mode? The only thing I find is the RoI waypoint in case the drone is flying a auto mission.

**Comment by ne0fhyk** [comment]
@Teemperor the functionality is [there](https://github.com/DroidPlanner/DroneKit-Android/blob/e380a67984ceff50897733c2eae7db3728cb5839/dependencyLibs/Core/src/org/droidplanner/core/MAVLink/command/doCmd/MavLinkDoCmds.java#L12-L26) but it's not exposed through the api. 

Should be an easy add though. Would you be interested in tackling it?

**Comment by Teemperor** [comment]
Yeah, sure. I'll make a pull request.

**Comment by Teemperor** [comment]
See #169

**Comment by ne0fhyk** [comment]
Fixed by #169
