### ISSUE TITLE
Invalid Tower-Pebble link 

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/DroneKit-Android#181]
The link to the Tower-Pebble **Android companion app** in the [Android DroneKit documentation](http://collabedit.com/b59c7) is invalid.

**Comment by djmedina** [comment]
Just a _comment_, but do we really want to start by pulling an existing project from github, wouldn't it be more useful if we start with a blank project? 

This bullet list looks a little off
![Bullet List](http://imgur.com/Wwf9ewy)

I would add more spacing between sections. This comment also applies to the Hello Drone tutorial
![Spacing](http://imgur.com/UjHtblI)

This link is dead:
[PebbleCommunicatorService](https://github.com/DroidPlanner/tower-pebble/blob/master/Android/src/main/java/org/droidplanner/Pebble/PebbleCommunicatorService.java)

We should have single formatting for flight modes. I see modes between quotes, and some other times in a different font.

Everything looks great. It seems like we are assuming that our audience has some experience developing watch applications, which is a valid assumption to make.
