### ISSUE TITLE
Tower-Pebble guide review

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/DroneKit-Android#183]
The Tower-Pebble guide is live on the [Android DroneKit site](http://android.dronekit.io/pebble_app.html).
Comments and feedback welcomed!

**Comment by ne0fhyk** [comment]
@hamishwillee once this is reviewed, could we publish a blog about it on diydrones.

**Comment by ne0fhyk** [comment]
@djmedina @phmagic @mrpollo @kaitlynhova Can you review and provide feedback, thanks!

**Comment by djmedina** [comment]
Do we make comments on github?

**Comment by ne0fhyk** [comment]
@djmedina yep, here or on PR #181
