### ISSUE TITLE
Rename 3DR Services to DroneKit Services

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/DroneKit-Android#203]

**Comment by ne0fhyk** [comment]
@phmagic @hamishwillee @mrpollo @tcr3dr thoughts?

**Comment by tcr3dr** [comment]
I support this, as it's less confusing for a developer. My only reservation would be if an end-user has issue with installing DroneKit Services vs. 3DR Services; would there be a huge impact there?

**Comment by hamishwillee** [comment]
Yes, good idea. @tcr3dr I don't think a new user would find this an issue. More concerned about someone updating - would they need to install a new package or would this be a silent update to the "old" 3DRServices?

**Comment by ne0fhyk** [comment]
Hamish, this would be an update to the old 3DR Services app.
I don't think it's much of a problem since most users don't interact with
the 3DR Services, only with its clients apps.

--
Fredia Huya-Kouadio
Android Tech Lead, 3D Robotics
fredia@3dr.com

**Comment by hamishwillee** [comment]
In that case the only issue is making sure that the transition is managed in the docs. With the actual names of file locations (e.g. to examples, github repos, etc) and package names (e.g. code libraries) change or is this just a "UI-level" change?

**Comment by ne0fhyk** [comment]
From the last DK meeting, a name change wasn't judged necessary.
