### ISSUE TITLE
Add support for gimbals attitude read/write

### ISSUE THREAD

**Issue by alextel69** [DroidPlanner/DroneKit-Android#44]
E.g. read/write gimbals roll, pitch, yaw via Mavlink message (radio output is not a clean design).
Additionally, add option to control copters yaw (for example, if gimbal is 2-axis)

**Comment by alextel69** [comment]
Any options?

**Comment by ne0fhyk** [comment]
@alextel69 looking into it.

**Comment by alextel69** [comment]
@ne0fhyk Best solution from my viewpoint would be creating Gimbal class, then obtaining via getGimbal.

**Comment by ne0fhyk** [comment]
@alextel69 I'm running out of time to implement this one. Would you be able to provide a PR with an implementation similar to the `SET_RELAY` api addition?

**Comment by alextel69** [comment]
@ne0fhyk good idea! Will this consider .aidl and server library?
By the way, I need not only mission, but nonmission (command) access as well

**Comment by squilter** [comment]
@ne0fhyk am I modeling it after [this](https://github.com/DroidPlanner/DroneKit-Android/commit/a29ebcbdec4039b1d3bd31d27f14b862597de501)?

**Comment by ne0fhyk** [comment]
@squilter yea.

**Comment by hamishwillee** [comment]
@mrpollo - this would be useful for DroneKit-Python.

**Comment by ne0fhyk** [comment]
Fixed by #173
