### ISSUE TITLE
Replace droneapi with dronekit

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/DroneKit-Android#79]
Refractor classes and documentation to reflect the name change from droneapi to DroneKit.

**Comment by phmagic** [comment]
Repo name: DroneKit-Android

Maven Lib name: DroneKit
Client lib name: DroneKit
Any backend name: DroneKit

App name: 3DR Services

**Comment by ne0fhyk** [comment]
@phmagic the current client lib maven repo is @ https://bintray.com/fredia/maven/3dr-services-lib/view.
It's setup under my own account. I believe there's a way to transfer the repo, but that needs to be looked into.

Is the client lib name `dronekit` or `dronekit-lib` or `dronekit-android-lib` in case we release a non-android java binding in the future.
