### ISSUE TITLE
USB double connection bug

### ISSUE THREAD

**Issue by alextel69** [DroidPlanner/DroneKit-Android#83]
If you connect 3DR Radio to your phone/tablet, but copter is not in range, and after that try to connect 2 times via USB, first try will fail (as it should be), but second will succeed. This error is cyclic e.g. if you disconnect, then connect again first attempt will fail, second will succeed and so on.

Also, if you unplug 3DR Radio when connection is established, AttributeEvent.STATE_DISCONNECTED will occur. But after fake connection described above is established, unplugging creates NPE MavLinkConnection.java:232.

**Comment by ne0fhyk** [comment]
Fixed by PR #121
